
project_id = "fnukymxxxcbjbqzzjzli"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true

[functions]
[functions.generate-game]
verify_jwt = false
[functions.logs]
verify_jwt = false
[functions.download]
verify_jwt = false
[functions.build]
verify_jwt = false
[functions.improve]
verify_jwt = false
