// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnukymxxxcbjbqzzjzli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudWt5bXh4eGNiamJxenpqemxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjM1MjAsImV4cCI6MjA2MTIzOTUyMH0.LNMXRuOOARCaikpoSjmQIhA5h1W39E9sS2gzp-zrvWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);